### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by nimma0001** [zyndex-drive/server#52]
How to deploy on worker.dev

**Comment by tks18** [comment]
This Cannot be Deployed on a Cloudflare worker. This is a NodeJs Server

**Comment by nimma0001** [comment]
> This Cannot be Deployed on a Cloudflare worker. This is a NodeJs Server

Can I deploy with termux or other Android app

**Comment by tks18** [comment]
In its Current State you cannot, But Soon you can Deploy it on AWS, Firebase, Heroku, etc, etc..

**Comment by nimma0001** [comment]
Thanks will wait for heroku update

**Comment by hackevil** [comment]
@tks18 any possiblity for a deployment guide, its been in development for months but i cannot deploy it coz i am a noob, it will be handy if you can write a guide.
